### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by SoulzStudios** [wrapper-offline/wrapper-offline#11]
My internet is on its highest and there's this error that tells me that there's a connection error and it doesn't let me save my vids or use any voices.

**Comment by funbuket9** [comment]
I have this same problem too. Have a good internet connection but just will not save. Then I go exit the program and reopen it (losing all of my progress). Says "localhost refused to connect" even though I have an internet connection. I don't think there is any fix to this issue because I think it's just the browser that it's using and not the actual program itself.
