### ISSUE TITLE
No whiteboard and inofgraphics

### ISSUE THREAD

**Issue by DaFTAMaker** [wrapper-offline/wrapper-offline#184]
I really need Whiteboard Animation and Video Infographics in my Wrapper Offline. But my computer won't let me get it. No matter how hard I try. I just won't get those two themes in there.

**Comment by SimplyA-Coder** [comment]
These business themes are not included due to piracy, as they are not included and probably will never be implemented. Currently, only GoAnimate Wrapper supports Whiteboard Animation (not Video Infographics). I don't even think any LVM has Video Infographics and never will. Plus, why do you need business themes? There's plenty of good themes implemented like Lil' Peepz, Comedy World, Stick Figure, Cartoon Classics, Space Citizens and more.
