### ISSUE TITLE
Characters won't load when creating a video.

### ISSUE THREAD

**Issue by CrazyCube32** [wrapper-offline/wrapper-offline#194]
It was working the first time. But when I created characters on Wrapper, they won't load when I try to use them on a video. Is there any solution to this situation? I tried restarting the app and even restarting my computer. I am using Wrapper Offline on a Mac.

**Comment by SimplyA-Coder** [comment]
In case you don't know, Wrapper: Offline is definitely not prone to run on a Mac due to MacOS being strict on security, which doesn't trust files. Unfortuantely, Wrapper: Offline was first designed for Windows and Linux which best work on those operating systems. As long as you get a different operating system you'll be fine. (For backup I recommend saving all movies and assets into a cloud file storage, such as Drive, Mega, Dropbox or others.)

**Comment by JBanimater700** [comment]
Really? Because I installed Wrapper Offline on my Mac, and It works just fine.

**Comment by CrazyCube32** [comment]
Did you download a new Wrapper: Offline version that fixes the problems of that on the Mac?
