### ISSUE TITLE
Error connect 

### ISSUE THREAD

**Issue by EthanAnimate** [wrapper-offline/wrapper-offline#260]
When i try to write joey voice an brian voice longer and when i generate it the title error connect something would just appered up and i can't seem to don't know why, so i hope that some of you guys would give me advice

**Comment by JBanimater700** [comment]
Those are Polly voices. And according to a user, the polly voices are heavily affected by the error. It's also because you're adding in way too many text to speech prompts at the same time. I would suggest using either ttsmp3.com, or readloud.net. Or you can wait a while and check back to see if it happens again.
