### ISSUE TITLE
TypeError: Cannot read property 'subtype' of undefined

### ISSUE THREAD

**Issue by NathanSaturnBOi** [Wrapper-Offline/wrapper-offline#46]
Whenever I try to load a video or something with something that's used in the _CACHE folder at some point, this error comes up & crashes the npm & shows this error below:

TypeError: Cannot read property 'subtype' of undefined
at Object.packXml (...\wrapper\movie\parse.js:584:41)

Is there a workaround or a fix for this?

**Comment by NathanSaturnBOi** [comment]
Here's also the proof on this I screenshotted
![proof](https://user-images.githubusercontent.com/60941727/118333907-6c15fc00-b4c1-11eb-9d96-91f744b6806e.PNG)

**Comment by NathanSaturnBOi** [comment]
Here's also the proof on this I screenshotted
![proof](https://user-images.githubusercontent.com/60941727/118343247-9d4ff580-b4dc-11eb-9c7a-4301850212df.PNG)

**Comment by CrystalVulpine** [comment]
I'm not even sure what they're trying to do here. It looks like they are confusing the `sound` case with `asset`, as `asset` uses and produces sound data instead of general asset data. `assetTypes` only loads the desired information in the sound case, but they still try to read from it in the asset one so it of course fails and returns an undefined value.

parse.js didn't exist at all until just a few weeks ago and the amount of code there is huge, so my guess is that this is the buggy result of a bunch of copying and pasting.

**Comment by zoccorus** [comment]
@RegularSpark close this
